### ISSUE TITLE
Request: Adding an License

### ISSUE THREAD

**Issue by xrxrxrxr** [loinesg/tower-defence#1]
Hello Mr. Loines,

is it possible that you can add an open source license to this project?
In one of my university courses, we use your game to develop an AI able to play the game.

We would really appreciate it!

**Comment by loinesg** [comment]
Hi,

I'm not planning to make any modifications or add a license to this project at the moment as it's primarily intended as a portfolio item.

Sorry for any inconvenience this causes.

George
